### ISSUE TITLE
Hata Mesajı Hakkında

### ISSUE THREAD

**Issue by bighat3** [onistok/PythonFloodAttackDDos#1]
Merhaba, program çalıştığında hata veriyor.

  File "atak.py", line 102
    try:
    ^
IndentationError: expected an indented block

bilginiz olsun iyi çalışmalar.

**Comment by onistok** [comment]
#print ('ssl olmadi') şu satırdaki yorumu kaldırınız, düzelecektir.

**Comment by onistok** [comment]
commit ettim.
